# Generated by Django 6.0.2 on 2026-02-11 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Company name, e.g. 'Acme Corporation'", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Brief description or remarks about the company')),
                ('logo_url', models.URLField(blank=True, help_text='URL to company logo image', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete — set to False instead of deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Primary email — used as login username', max_length=254, unique=True)),
                ('full_name', models.CharField(help_text="User's display name", max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', help_text='Phone number', max_length=20)),
                ('avatar_url', models.URLField(blank=True, help_text="URL to user's avatar image", null=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('dept_head', 'Department Head'), ('employee', 'Employee')], default='employee', help_text='System role — controls permissions', max_length=20)),
                ('job_title', models.CharField(blank=True, default='', help_text="Display title, e.g. 'Marketing Head', 'Frontend Developer'", max_length=255)),
                ('is_password_temp', models.BooleanField(default=True, help_text='True = user must reset password on next login')),
                ('is_onboarded', models.BooleanField(default=False, help_text='True = user has completed onboarding')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete — set to False instead of deleting')),
                ('is_staff', models.BooleanField(default=False, help_text='Required by Django for admin panel access')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone, e.g. 'Asia/Kolkata'", max_length=50)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Preferred UI theme', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Which user created this user? Null if created by Super Admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, help_text='The company this user belongs to. Null for Super Admins.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the reset token', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='Token expires after this time (1 hour from creation)')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used (NULL = not used yet)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('temp_password_set', 'Temp Password Set'), ('company_created', 'Company Created'), ('company_updated', 'Company Updated'), ('company_deactivated', 'Company Deactivated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('user_role_changed', 'User Role Changed'), ('onboarding_completed', 'Onboarding Completed')], help_text='What happened', max_length=30)),
                ('target_type', models.CharField(blank=True, default='', help_text="Type of object affected: 'user', 'company', etc.", max_length=50)),
                ('target_id', models.UUIDField(blank=True, help_text='ID of the affected object', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Extra details as JSON, e.g. {'old_role': 'employee', 'new_role': 'admin'}")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='Which company this action relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='accounts_au_company_54fc08_idx'), models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_14f360_idx'), models.Index(fields=['action', '-created_at'], name='accounts_au_action_f18cdc_idx')],
            },
        ),
    ]
