# Generated by Django 6.0.2 on 2026-02-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_secondary',
            field=models.EmailField(blank=True, help_text='Optional backup/secondary email', max_length=254, null=True),
        ),
    ]
