# Generated by Django 6.0.2 on 2026-02-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_secondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme_preference',
        ),
    ]
