# Generated by Django 6.0.2 on 2026-02-19 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_action_team_teammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('temp_password_set', 'Temp Password Set'), ('company_created', 'Company Created'), ('company_updated', 'Company Updated'), ('company_deactivated', 'Company Deactivated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('user_role_changed', 'User Role Changed'), ('onboarding_completed', 'Onboarding Completed'), ('team_created', 'Team Created'), ('team_updated', 'Team Updated'), ('team_archived', 'Team Archived'), ('member_added', 'Member Added to Team'), ('member_removed', 'Member Removed from Team'), ('member_role_changed', 'Member Role Changed'), ('user_invited_to_team', 'User Invited to Team'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_moved', 'Task Moved'), ('task_deleted', 'Task Deleted'), ('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned')], help_text='What happened', max_length=30),
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='accounts.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('position', models.FloatField(default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.boardcolumn')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks_to_others', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='accounts.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('team', 'position'), name='unique_column_position_per_team'),
        ),
        migrations.AddConstraint(
            model_name='taskassignee',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_assignee_per_task'),
        ),
    ]
