# Generated by Django 6.0.2 on 2026-02-26 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_action_boardcolumn_task_taskassignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('temp_password_set', 'Temp Password Set'), ('company_created', 'Company Created'), ('company_updated', 'Company Updated'), ('company_deactivated', 'Company Deactivated'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('user_role_changed', 'User Role Changed'), ('onboarding_completed', 'Onboarding Completed'), ('team_created', 'Team Created'), ('team_updated', 'Team Updated'), ('team_archived', 'Team Archived'), ('member_added', 'Member Added to Team'), ('member_removed', 'Member Removed from Team'), ('member_role_changed', 'Member Role Changed'), ('user_invited_to_team', 'User Invited to Team'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_moved', 'Task Moved'), ('task_deleted', 'Task Deleted'), ('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned'), ('comment_added', 'Comment Added'), ('comment_edited', 'Comment Edited'), ('comment_deleted', 'Comment Deleted')], help_text='What happened', max_length=30),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTeamView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='accounts.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'team'), name='unique_user_team_view')],
            },
        ),
    ]
